### ISSUE TITLE
USER STORY #4 - Specialist Search Result Page and Filtering

### ISSUE THREAD

**Issue by easybulb** [easybulb/healmate#18]
As a **patient**, I want to **search for specialists by category (e.g., Dermatologist, Psychologist)** so that **I can find a doctor that meets my needs**.

**Acceptance Criteria**
* Patients can search for specialists by specialty, location, and availability.
* The search results page displays accurate data based on filters.
* Patients see a message if no doctors are found.
* Doctors have profiles displaying relevant information.

**Task**
- [x] Create search results page with specialists details search result, image, number of results and pagination.
- [x] Integrate search results with the appointment booking system.
- [x] Connect the home page search bar to the existing search and filter system.
- [x] Test search and filtering functionality for edge cases.
