### ISSUE TITLE
Dev Task #2 - Create Django Project

### ISSUE THREAD

**Issue by easybulb** [easybulb/healmate#2]
As a **developer**, I can **create the Django project and app** so that **I can set up the database**.

**Acceptance Criteria**
* Create the Django project HealMate directory
* Create the accounts app
* PROJ_NAME=HealMate APP_NAME=accounts

**Tasks**
- [x] Create the Django project HealMate directory
- [x] Create the accounts app
- [x] Add it to the list of INSTALLED_APPS
- [x] Migrate the changes to the database
- [x] Add 8000 port url to ALLOWED_HOSTS
- [x] python3 manage.py runserver to test
